name: back2normal
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2
  - asgiref=3.3.0
  - astroid=2.4.2
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bokeh=2.3.0
  - branca=0.4.2
  - brotlipy=0.7.0
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.6
  - cycler=0.10.0
  - decorator=4.4.2
  - django=3.1.2
  - folium=0.12.0
  - freetype=2.10.4
  - idna=2.10
  - importlib_metadata=2.0.0
  - iniconfig=1.1.1
  - intel-openmp=2019.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - isort=5.7.0
  - jinja2=2.11.3
  - jpeg=9d
  - jupyter_core=4.7.1
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libpng=1.6.37
  - libpq=12.2
  - libsodium=1.0.18
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mccabe=0.6.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - more-itertools=8.5.0
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.1.5
  - parso=0.8.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=20.3.3
  - pluggy=0.13.1
  - psycopg2=2.8.5
  - ptyprocess=0.7.0
  - py=1.9.0
  - pycparser=2.20
  - pylint=2.6.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=6.1.1
  - python=3.6.13
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2021.1
  - pyyaml=5.4.1
  - readline=8.1
  - requests=2.25.1
  - six=1.15.0
  - sqlite=3.33.0
  - sqlparse=0.4.1
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.1
  - traitlets=4.3.3
  - typed-ast=1.4.2
  - typing_extensions=3.7.4.3
  - urllib3=1.26.3
  - wcwidth=0.2.5
  - wheel=0.36.2
  - wrapt=1.11.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - backoff==1.10.0
    - bleach==3.3.0
    - click==7.1.2
    - click-plugins==1.1.1
    - cligj==0.7.1
    - defusedxml==0.7.0
    - entrypoints==0.3
    - fiona==1.8.18
    - geopandas==0.9.0
    - importlib-metadata==3.7.0
    - ipykernel==5.5.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.11
    - jupyter-console==6.2.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - mistune==0.8.4
    - munch==2.5.0
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.5.1
    - notebook==6.2.0
    - pandocfilters==1.4.3
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.16
    - pygments==2.7.4
    - pyproj==3.0.1
    - pyrsistent==0.17.3
    - pyzmq==22.0.3
    - qtconsole==5.0.2
    - qtpy==1.9.0
    - ratelimit==2.2.1
    - send2trash==1.5.0
    - setuptools==54.0.0
    - shapely==1.7.1
    - sodapy==2.1.0
    - terminado==0.9.2
    - testpath==0.4.4
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1